version: "3.3"

services:
  redis:
    restart: always
    ports:
      - "7379:6379"

  redis-commander:
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - HTTP_USER=root
      # - HTTP_PASSWORD=root
    ports:
      - "38081:8081"
