// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trade/order/buy": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "買",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "買",
                "parameters": [
                    {
                        "description": "參數",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqs.OrderPostBuy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "資料",
                        "schema": {
                            "$ref": "#/definitions/resp.Base"
                        }
                    }
                }
            }
        },
        "/trade/order/sell": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "賣",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "賣",
                "parameters": [
                    {
                        "description": "參數",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqs.OrderPostSell"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "資料",
                        "schema": {
                            "$ref": "#/definitions/resp.Base"
                        }
                    }
                }
            }
        },
        "/trade/order/test": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "測試",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "測試",
                "parameters": [
                    {
                        "description": "參數",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqs.OrderPostTest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "資料",
                        "schema": {
                            "$ref": "#/definitions/resp.Base"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "reqs.OrderPostBuy": {
            "type": "object",
            "required": [
                "price",
                "quantity"
            ],
            "properties": {
                "price": {
                    "type": "number",
                    "default": 10
                },
                "quantity": {
                    "type": "integer",
                    "default": 5
                }
            }
        },
        "reqs.OrderPostSell": {
            "type": "object",
            "required": [
                "price",
                "quantity"
            ],
            "properties": {
                "price": {
                    "type": "number",
                    "default": 10
                },
                "quantity": {
                    "type": "integer",
                    "default": 5
                }
            }
        },
        "reqs.OrderPostTest": {
            "type": "object",
            "required": [
                "price",
                "quantity",
                "run_times"
            ],
            "properties": {
                "price": {
                    "type": "number",
                    "default": 10
                },
                "quantity": {
                    "type": "integer",
                    "default": 5
                },
                "run_times": {
                    "type": "integer",
                    "default": 50
                }
            }
        },
        "resp.Base": {
            "type": "object",
            "properties": {
                "data": {},
                "event_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "zerologix-homework",
	Description:      "homework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
